### ISSUE TITLE
Configuration of the Docker Container

### ISSUE THREAD

**Issue by Jolly5** [UMEssen/DICOM-RST#14]
According to the [Documentation](https://umessen.github.io/DICOM-RST/configuration.html), DICOM-RST needs to be configured via a configuration file (config.yaml) located next to the binary.

To me, a Docker novice, it is sadly unclear how I am supposed to get that configuration file into the docker image.
Can you elaborate this here or improve the documentation on that regard?

Thanks in advance!

**Comment by nickamzol** [comment]
You can use Docker [volumes](https://docs.docker.com/storage/volumes/) to mount a local file into the container.

The configuration file is expected to be located in the root directory of the container (`/config.yaml`).
To mount a local file named `myconfig.yaml`, you can use the `-v` flag with a value of `./myconfig.yaml:/config.yaml:ro`.

Take a look at [/debug/simple-setup](https://github.com/UMEssen/DICOM-RST/tree/31ac152b57fecd6d8d1c51486434e9452aace032/debug/simple-setup) for an example setup with Docker Compose that mounts a custom config file into the container. 

Fixed in 31ac152b57fecd6d8d1c51486434e9452aace032.
